zuul:
  routes:
    order:
      path: /order/**
      serviceId: producer-to-rabbit-simInformation
      stripPrefix: false
    sendInfo:
       path: /sendInfo/**
       serviceId: client-to-producer-messages
       stripPrefix: false

eureka:
  
  client:
    serviceUrl:
      defaultZone: http://admin:admin@eureka-server:8761/eureka/
      
 
 
server:
  port: 8181
  
spring:
  application:
    name: zuul-proxy
  zipkin:
    service:
      name: zull-proxy
    baseUrl: http://zipkin-server:9411
    sender:
      type: web
    sampler:
      probability: 1.0
    enabled: true
    http:
      url: http://zipkin-server:9411
  sleuth:
    enabled: true
    sampler:
      probability: 1.0
      percentage: 1.0
    annotation:
      enabled: true
    
ribbon: 
  ConnectTimeout: 6000
  ReadTimeout: 60000