server:
  port: ${PORT:0}

spring:
  application:
    name: producer-to-rabbit-simInformation
  rabbitmq:
    host: microservicios-rabbitmq38
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        simChannel:
          destination: simSend
          contentType: application/json
  zipkin:
    service:
      name: producer-to-rabbit-simInformation
    baseUrl: http://zipkin-server:9411
    sender:
      type: web
    sampler:
      probability: 1.0
    enabled: true
    http:
      url: http://zipkin-server:9411
  sleuth:
    enabled: true
    sampler:
      probability: 1.0
      percentage: 1.0
    annotation:
      enabled: true

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://admin:admin@eureka-server:8761/eureka/
      #,http://my-eureka-server-valencia.com:9002/eureka/,http://my-eureka-server-bilbao.com:9003/eureka/,http://my-eureka-server-barcelona.com:9001/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

    
logging:
  path: C:\EUREKA\logs\sim-service
  level:
    root: INFO
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} %5p [${spring.application.name},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-}] %m%n'
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %5p [${spring.application.name},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-}] %m%n'
  file: ${logging.path}/
  config: classpath:logback-spring.xml